const TaskData = [
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Pending',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Pending',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Pending',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Pending',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Pending',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Pending',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Pending',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Pending',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Pending',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        bids: [
            {
                name: 'Brunzo Z.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'I have many years of experience',
                budget: '$40',
                timeAgo: 'About 20 min ago'
            },
            {
                name: 'Mohammed I.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5113175/daf2201a-c641-4b30-9615-1f52d88b1eb8-04da006b57a894675d67ccda1006dc66.jpg?width=136&height=136',
                description: 'Hi, I have 2 tonne van, I have blankets and straps needed, happy to do the job, I’ll look after your stuff, I’ve done furniture removal before, check my 5 star customers feedback',
                budget: '$38',
                timeAgo: 'About 1 hour ago'
            },
            {
                name: 'Jordan K.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/5441221/image-89efc0365cc985ed1656290545d9c015.jpg?width=136&height=136',
                description: 'Two removalists with a large 4 ton van with a manual ramp too load up heavy items, all the moving equipment, tie downs, safety blankets, trolleys, dollys. We are fully insured. Price includes all expenses on my end, includes AirTasker fee, Fuel, Labour, GST, Dumping fees.',
                budget: '$45',
                timeAgo: 'About 2 days ago'
            },
            {
                name: 'Shivam Shukla.',
                imgSrc: 'https://eu7cmie.cloudimg.io/v7/https://assets-airtasker-com.s3.amazonaws.com/uploads/user/avatar/1243367/image-830d0c54d494305f887b46065b48fccd.jpg?width=136&height=136',
                description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.',
                budget: '$31',
                timeAgo: 'About 3 days ago'
            },
        ]
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Cancel',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Cancel',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Cancel',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Cancel',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Cancel',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Cancel',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Cancel',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Cancel',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Cancel',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        remark: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mr Denn jorkash',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mr Dark Mercury',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Paid',
        rating: 5,
        completedBy: 'Mr Varun Tirpathi',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Paid',
        rating: 5,
        completedBy: 'Mrs Anjali Singh',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mrs Simran Jaiswal',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Paid',
        rating: 5,
        completedBy: 'Mr Virendra Tomer',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mr Gourav Singhaniya',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mrs Akansha Patel',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        status: 'Completed',
        dueDate: 'Fri 20th Dec 2022',
        payment: 'Pending',
        rating: 5,
        completedBy: 'Mrs Divya Mourya',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Dec 2022',
        status: 'In Progress',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov 2022 4:44 PM',
        dueDate: 'Mon 22th Dec 2022',
        status: 'In Progress',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec 2022 4:44 PM',
        dueDate: 'Fri 29th Dec 2022',
        status: 'In Progress',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Jan 2023',
        status: 'In Progress',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Nov 2023',
        status: 'In Progress',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Dec 2022',
        status: 'In Progress',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Move furniture around the house to have laminate layed',
        price: 100,
        location: 'Queenstown SA',
        remote: 'Remote',
        date: 'Fri, 2 Dec 2022 4:44 PM',
        dueDate: 'Fri 20th Dec 2022 7:00 AM',
        status: 'In Progress',
        offers: 7,
        postedBy: 'Deepak Singh Rathore',
        categoryList: 'Furniture Assembly , Interior Designer',
        language: 'English , Japanese , Vietnamese',
        skills: 'CSS, html',
        learningMethod: 'Text only',
        description: 'We live in a permanent caravan & annex, we did like to extend the annex out under the small carport thats too small for car We have other small jobs too.',
    },
    {
        taskName: 'Repair plantation shutter Repair plantation shutter',
        price: 150,
        location: 'Prospect SA',
        remote: 'Remote',
        date: 'Thu, 17 Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Dec 2022',
        status: 'In Progress',
        offers: 4,
        postedBy: 'Tarun Verma',
        categoryList: 'Business , Car Body Work , Cleaning',
        language: 'English , Arabic , 	Mandarin Chinese',
        skills: 'Flutter, javscript, React Native',
        learningMethod: 'Phone-call only',
        description: 'We need someone who can build us an end-to-end event stand for an upcoming event in Sydney, this person/ team needs to have previous stand event building experience (and show us examples).',
    },
    {
        taskName: 'Supply and install of facia and gutter including flashings',
        price: 40,
        location: 'Kensington Park SA',
        remote: 'Remote',
        date: 'Sat,19th Nov 2022 4:44 PM',
        dueDate: 'Fri 20th Dec 2022',
        status: 'In Progress',
        offers: 11,
        postedBy: 'Himanshu Suratiya',
        categoryList: 'Accountants , Bakers',
        language: 'English , Spanis , korean',
        skills: 'React.js, javscript, html',
        learningMethod: 'Phone-call & Text',
        description: 'Your task may be impacted. See Safety Centre for info. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
]

export default TaskData;